kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-configmap
  namespace: default
  labels:
    app: redis-cluster
data:
  redis.conf: |-
    appendonly yes
    cluster-enabled yes
    cluster-config-file /etc/redis/nodes.conf
    cluster-node-timeout 5000
    dir /etc/redis
    port 6379
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    app: redis-cluster
  name: redis-cluster 
  namespace: default
spec:
  replicas: 4 
  serviceName: redis-cluster
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      name: redis-cluster
      labels:
        app: redis-cluster
    spec:
      containers:
      - name: redis
        image: 172.31.87.111:5000/redis
        imagePullPolicy: Always
        command: ["redis-server","/etc/redis/redis.conf"]
        volumeMounts: 
        - name: data
          mountPath: /mnt
        - name: config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf
      volumes:
      - name: config
        configMap:
          name: redis-configmap
          items:
          - key: redis.conf
            path: redis.conf
      - name: data
        hostPath:
          path: /etc/redis

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: redis-cluster
  name: redis-cluster
  namespace: default
spec:
  ports:
  - name: http
    port: 6379
  clusterIP: None
  selector:
    app: redis-cluster

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: redis-cluster
  name: redis-svc-cluster
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 6379
    targetPort: 6379
    nodePort: 30379
  selector:
    app: redis-cluster
